apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: devsheriff-backend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
    spec:
      serviceAccountName: devsheriff-runner@alhichdevsheriff.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 120
      containers:
        - image: us-central1-docker.pkg.dev/alhichdevsheriff/devsheriff-images/backend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1Gi
              cpu: "1"
          env:
            - name: ENVIRONMENT
              value: production
            - name: FIRESTORE_PROJECT_ID
              value: alhichdevsheriff
            - name: GCP_PROJECT_ID
              value: alhichdevsheriff
